run:
linters:
  enable:
  - errcheck
  - goimports
  - gosec
  - gocritic
  - golint
  - gocyclo
  - prealloc
  - wsl
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

